# Generated by Django 6.0.5 on 2026-05-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('khqr', 'KHQR (ABA / ACLEDA)'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20),
        ),
    ]
