# Generated by Django 6.0.5 on 2026-06-08 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAPI', '0003_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
